#!/usr/bin/env python3
"""cut-gold-split.py — audit-aware, deterministic split generator (M3B).

WHY THIS SCRIPT EXISTS
======================
The original GHARIBO-Research-Gold-v0.1 split used seed 3407 and was generated by
a script that was never committed. As a result the split was NOT reproducible from
anything on disk, and — worse — its TEST split contained 10 of the 100 examples
that the M3B gold audit inspected. Inspecting TEST examples contaminates the
held-out set, so that split had to be superseded.

This generator is committed source. It is the single, auditable definition of the
current split:

  * NEW seed (see SPLIT_SEED below);
  * the 100-example audit cohort is QUARANTINED into TRAIN / VALIDATION, so
    audited INTERSECT TEST is guaranteed to be empty by construction;
  * no gold example content is modified — split files are a partition of the raw
    lines of the flat corpus, written back byte-for-byte;
  * the assignment is keyed by the content hash of each record, so re-cutting
    identical inputs on any machine reproduces identical splits and hashes,
    independent of input order.

ALGORITHM (exact)
=================
  lineHash(r)   = sha256(utf-8(raw JSONL line bytes, trailing CR stripped))
  k(r)          = sha256(utf-8(str(seed) + ":" + lineHash(r)))
  ordering      = ascending by (k(r), lineHash(r))
  splitHash(S)  = sha256(utf-8("\n".join(sorted(lineHash(r) for r in S))))
  datasetHash   = sha256(utf-8("\n".join(sorted(lineHash(r) for r in ALL))))

  nTrain = floor(N * 0.8); nVal = floor(N * 0.1); nTest = N - nTrain - nVal
  TEST   = the last nTest records of the non-cohort ordering
  TRAIN  = the first nTrain records of (cohort + remaining non-cohort) ordering
  VALID  = the remaining nVal records of that same ordering

Determinism: same inputs -> byte-identical split files and byte-identical
dataset-card.json. No wall-clock value is written.

Usage:
    python scripts/split/cut-gold-split.py
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

# The shared audit-cohort definition lives in scripts/. Import it so the split and
# the audit can never disagree about which examples were inspected.
SCRIPTS_DIR = Path(__file__).resolve().parent.parent
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

from gold_cohort import (  # noqa: E402  (import after sys.path is prepared)
    AUDIT_SEED,
    AUDIT_SIZE,
    REPO_ROOT,
    audited_line_indices,
)

FLAT_PATH = REPO_ROOT / "data/processed/training-examples/gharibo-research-gold-v0.1-examples.jsonl"
SPLIT_DIR = REPO_ROOT / "data/processed/gharibo-research-gold-v0.1"
CARD_PATH = SPLIT_DIR / "dataset-card.json"

# A NEW split seed. Chosen so the superseded seed-3407 cut can never be confused
# with this one; it encodes the M3B session date (2026-09-14) for auditability.
SPLIT_SEED = 20260914
RATIOS = {"train": 0.8, "validation": 0.1, "test": 0.1}

# Historical facts about the SUPERSEDED split. Recorded verbatim so the
# supersession is auditable even after the on-disk card is overwritten.
SUPERSEDED_SEED = 3407
SUPERSEDED_HASHES = {
    "trainSplitHash": "61afb232fa5e5783463499d1ee24355c52cf56edc5fe11b3bda48795152c6a6c",
    "validationSplitHash": "f884c9a953f75a348ed257f84140878a519d6c9f96c9f39accd2660a51095906",
    "testSplitHash": "959068e5451874ab5c3398584c0187dfdb4815c6d00d3a37ca69a54d8f79f11b",
}
SUPERSEDED_REASON = (
    "TEST contamination — 10 of 100 audited examples were inspected; the seed-3407 "
    "split was not reproducible from any committed source"
)


def sha256_hex(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def read_flat_lines() -> list[str]:
    """Reads the flat corpus as raw lines (CR stripped, blank lines dropped)."""
    text = FLAT_PATH.read_bytes().decode("utf-8")
    lines = []
    for raw in text.split("\n"):
        line = raw[:-1] if raw.endswith("\r") else raw
        if line.strip() == "":
            continue
        lines.append(line)
    return lines


def split_hash(line_hashes: list[str]) -> str:
    return sha256_hex("\n".join(sorted(line_hashes)))


def main() -> int:
    print("=" * 70)
    print("GHARIBO M3B — audit-aware deterministic split generator")
    print("=" * 70)

    lines = read_flat_lines()
    total = len(lines)
    line_hashes = [sha256_hex(line) for line in lines]
    if len(set(line_hashes)) != total:
        raise SystemExit("ABORT: duplicate lines in the flat corpus — split identity is ambiguous")

    cohort = set(audited_line_indices())
    print(f"flat corpus          : {total} examples")
    print(f"audit cohort         : {len(cohort)} examples (seed {AUDIT_SEED})")

    # Deterministic keyed ordering.
    keyed = sorted(
        range(total),
        key=lambda i: (sha256_hex(f"{SPLIT_SEED}:{line_hashes[i]}"), line_hashes[i]),
    )
    non_cohort = [i for i in keyed if i not in cohort]

    n_train = int(total * RATIOS["train"])  # floor
    n_val = int(total * RATIOS["validation"])  # floor
    n_test = total - n_train - n_val

    if n_test > len(non_cohort):
        raise SystemExit("ABORT: not enough non-cohort examples to fill TEST without contamination")

    # TEST is drawn ONLY from non-cohort records → audited ∩ TEST = ∅ by construction.
    test = non_cohort[-n_test:]
    remaining_non_cohort = non_cohort[:-n_test]

    pool = sorted(cohort | set(remaining_non_cohort), key=lambda i: (
        sha256_hex(f"{SPLIT_SEED}:{line_hashes[i]}"),
        line_hashes[i],
    ))
    train = pool[:n_train]
    validation = pool[n_train:]

    splits = {"train": train, "validation": validation, "test": test}

    # Hard invariants — fail loudly rather than write a bad split.
    assert len(train) == n_train and len(validation) == n_val and len(test) == n_test
    assert not (set(train) & set(validation)) and not (set(train) & set(test))
    assert not (set(validation) & set(test))
    assert set(train) | set(validation) | set(test) == set(range(total))
    assert set(test) & cohort == set(), "ABORT: TEST contains audited examples"

    SPLIT_DIR.mkdir(parents=True, exist_ok=True)
    split_hashes = {}
    for name in ("train", "validation", "test"):
        indices = splits[name]
        payload = "\n".join(lines[i] for i in indices) + "\n"
        (SPLIT_DIR / f"{name}.jsonl").write_text(payload, encoding="utf-8", newline="\n")
        split_hashes[f"{name}SplitHash"] = split_hash([line_hashes[i] for i in indices])
        print(f"wrote {name}.jsonl   : {len(indices)} examples, hash {split_hashes[f'{name}SplitHash'][:12]}…")

    dataset_hash = split_hash(line_hashes)
    print(f"datasetHash          : {dataset_hash}")

    # ------------------------------------------------------------------ card
    card = json.loads(CARD_PATH.read_text(encoding="utf-8"))
    card["counts"] = {"totalExamples": total, "train": n_train, "validation": n_val, "test": n_test}
    card["splitPolicy"] = {
        "seed": SPLIT_SEED,
        "algorithm": "seeded-sha256-content-hash-with-audit-quarantine",
        "ratios": dict(RATIOS),
        "method": (
            "Deterministic hash-keyed assignment. lineHash(r)=sha256(raw JSONL line bytes); "
            "k(r)=sha256(str(seed)+':'+lineHash(r)); records ordered ascending by (k, lineHash). "
            "The 100-example M3B audit cohort is quarantined out of TEST. "
            "TEST=last nTest non-cohort records; TRAIN/VALIDATION partition (cohort + remaining "
            "non-cohort) in the same order."
        ),
        "lineHashAlgorithm": "sha256(utf-8(raw line bytes, trailing CR stripped))",
        "splitHashAlgorithm": "sha256(utf-8('\\n'.join(sorted(lineHash(r) for r in S))))",
        "auditQuarantine": {
            "auditSeed": AUDIT_SEED,
            "auditCohortSize": AUDIT_SIZE,
            "quarantinedInto": ["train", "validation"],
            "testAudited": 0,
        },
        "testHeldOut": True,
        "testPolicy": (
            "TEST is permanently held out — never used for training, tuning, prompt engineering, "
            "hyperparameter search, checkpoint selection, or few-shot examples."
        ),
    }
    card["hashes"] = {
        "datasetHash": dataset_hash,
        "trainSplitHash": split_hashes["trainSplitHash"],
        "validationSplitHash": split_hashes["validationSplitHash"],
        "testSplitHash": split_hashes["testSplitHash"],
    }
    card["supersededSplits"] = [
        {
            "seed": SUPERSEDED_SEED,
            "hashes": dict(SUPERSEDED_HASHES),
            "reason": SUPERSEDED_REASON,
            "supersededBy": {"seed": SPLIT_SEED, "hashes": dict(split_hashes)},
            "generator": "scripts/split/cut-gold-split.py",
        }
    ]
    card["splitProvenance"] = {
        "generator": "scripts/split/cut-gold-split.py",
        "cohortModule": "scripts/gold_cohort.py",
        "committed": True,
    }

    CARD_PATH.write_text(json.dumps(card, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote dataset-card.json: seed {SPLIT_SEED}")
    print("")
    print("audited ∩ TEST = 0 ✔   (cohort quarantined into TRAIN/VALIDATION)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
